name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    name: Generate project

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        syntax: [OCaml, Reason]
        package-manager: [Opam, Esy]

    env:
      SPIN_PROJECT_NAME: Demo
      SPIN_CREATE_SWITCH: false
      SPIN_AUTHOR_NAME: Jonh Doe
      SPIN_SYNTAX: ${{ matrix.syntax }}
      SPIN_PACKAGE_MANAGER: ${{ matrix.package-manager }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ocaml-base-compiler.4.12.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.12.0

      - run: npm install -g esy
        if: ${{ matrix.package-manager == 'Esy' }}

      - run: opam install spin

      - run: opam exec -- spin new . _generated -d -vv

      - run: make test
        working-directory: _generated
        if: ${{ matrix.package-manager == 'Opam' }}

      - run: esy test
        working-directory: _generated
        if: ${{ matrix.package-manager == 'Esy' }}
